"========================================================="
"                                                         "
"                    Vim Configuration                    "
"                                                         "
"                  Author: David Hagerty                  "
"                     Copyright 2018                      "
"                                                         "
"       My configuration for Vim, lovingly crafted.       "
"              Made for ease of use in macOS.             "
"                    Copy as you wish.                    "
"                But credit is appreciated.               "
"                                                         "
"========================================================="

"==============="
"  Keybindings  "
"==============="

" Set the Leader key to the spacebar
let mapleader = "\<Space>"

" Open this file for editing anywhere you are
nmap <leader>vr :sp $MYVIMRC<CR>

" Reload this configuration
nmap <leader>so :source $MYVIMRC<CR>

" Search without highlighting
nmap <leader>h :nohlsearch<CR>

" Jump forwards by paragraph. Jumps to the beginning then the end of 'paragraph'-type structures
nnoremap <expr> { len(getline(line('.')-1)) > 0 ? '{+' : '{-'

" Jump backwards by paragraph. Reverse of the above mapping
nnoremap <expr> } len(getline(line('.')+1)) > 0 ? '}-' : '}+'

" Disable arrow keys to encourage Vim's own movement paradigms
noremap <up> <nop>
noremap <down> <nop>
noremap <left> <nop>
noremap <right> <nop>

"==================="
"  Vundle Settings  "
"==================="

" Enable Vundle
set rtp+=~/.vim/bundle/Vundle.vim

" List plugins to manage
call vundle#begin()
  " Let Vundle manage itself
  Plugin 'gmarik/Vundle.vim'
  
  " The best git wrapper, period.
  Plugin 'tpope/vim-fugitive'
  
  " Easily handle comments
  Plugin 'tpope/vim-commentary'
  
  " Makes working with brackets, quotes, tags, etc easier
  Plugin 'tpope/vim-surround'
  
  " The secret sauce to make netrw better
  Plugin 'tpope/vim-vinegar'
  
  " Work with words better
  Plugin 'tpope/vim-abolish'
  
  " Better repeating support
  Plugin 'tpope/vim-repeat'
  
  " Support for auto-completing if/endif do/end type structures
  Plugin 'tpope/vim-endwise'
  
  " Add git diff information to the gutter
  Plugin 'airblade/vim-gitgutter'

  " Add syntax checking
  Plugin 'scrooloose/syntastic'

  " Add async build capabilities
  Plugin 'neomake/neomake'

  " Add new and better text targets for normal mode
  Plugin 'wellle/targets.vim'

  " Add a tagbar to browse tags
  Plugin 'majutsushi/tagbar'
  
  " Ease writing of XML/HTML by auto-closing tags
  Plugin 'vim-scripts/closetag.vim'
  
  " Auto-close parens, brackets, and braces
  Plugin 'jiangmiao/auto-pairs'

  " Set up a cool-looking statusline
  Plugin 'itchyny/lightline.vim'

  " Add fzf-style finding to vim
  Plugin 'junegunn/fzf.vim'

  " Add editorconfig support to vim
  Plugin 'editorconfig/editorconfig-vim'  

  " Add Gruvbox colorscheme to Vim
  Plugin 'morhetz/gruvbox'

  " Add Solarized colorscheme to Vim
  Plugin 'altercation/vim-colors-solarized'
  call vundle#end()

"==========="
"  General  "
"==========="

" Set the local encoding to UTF-8 and ignore any BOMs
set encoding=utf-8 nobomb

" Turn on filetype detection, and turn on filetype-based settings and indentation rules
filetype plugin indent on

" Enable syntax highlighting
syntax on

" Colorscheme settings
colorscheme solarized

" Gruvbox settings

let g:gruvbox_contrast_dark = 'soft'

" Always show the status bar
set laststatus=2

" Allow backspaces to wrap over indents, line breaks, and the start of Insert mode
set backspace=indent,eol,start

" Enable better command-line completion
set wildmenu

" Turn on wrapping lines (default is on, but this is to show I want this behavior)
set wrap

" Wrap lines at words, not characters
set linebreak

" Turn on spell checking for Git commit messages
autocmd Filetype gitcommit setlocal spell textwidth=72

"=========="
"  Search  "
"=========="

" Case-insensitive search, unless we use capital letters
set ignorecase
set smartcase

" Incrementally search
set incsearch

" Highlight search results
set hlsearch

"=========================="
"  Tab and Space Settings  "
"=========================="

" Set tab to two spaces
set tabstop=2

" An indent is the same width as tab
set shiftwidth=2

" Expand tab characters into space characters
set expandtab

" Automatically indent blocks
set smartindent

"======================"
"  Performance Tuning  "
"======================"

" Indicate a fast terminal connection
set ttyfast

" Limit the scrolling speed
if !has('nvim')
  set ttyscroll=3
endif

" Don't redraw while executing macros
set lazyredraw

"=========="
"  Cursor  "
"=========="

" Highlight the current line the cursor is on
set cursorline

" When the window is no longer active, do not highlight the cursor line
autocmd WinLeave * setlocal nocursorline

" Highlight the current column the cursor is in
set cursorcolumn

" When the window is no longer active, do not highlight the cursor column
autocmd WinLeave * setlocal nocursorcolumn

" Highlight the column after <textwidth> (default is 80 characters)
set colorcolumn=+1

"=================="
"  Line Numbering  "
"==================" 

" Turn on line numbering relative to the current line (default)
set relativenumber

" Set absolute line numbers while in Insert mode
autocmd InsertEnter * :set number

" Return to relative numbers outside of Insert mode
autocmd InsertLeave * :set relativenumber

" Set the fold level to the deepest level on reading a buffer
autocmd BufRead * normal zR

"==========================="
"  Lightline Configuration  "
"==========================="

set noshowmode

let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }

"==========================="
"  Plugin Related Settings  "
"==========================="

set rtp+=/usr/local/opt/fzf
nmap <leader>b :TagbarToggle<CR>
let g:syntastic_aggregate_errors=1
let g:syntastic_auto_loc_list=1
let g:EditorConfig_exclude_patterns = ['fugitive://.\*', 'scp://.\*']
command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --no-ignore --hidden --follow --glob "!.git/*" --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1, <bang>0)
